<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-DG8G23UU" failures="1" tests="6" name="prashantbhakuni.Test.AppointmentBookingTestCases" time="37.434" errors="0" timestamp="2024-06-03T19:24:23 IST" skipped="0">
  <testcase classname="prashantbhakuni.Test.AppointmentBookingTestCases" name="bookingFive" time="7.417"/>
  <testcase classname="prashantbhakuni.Test.AppointmentBookingTestCases" name="bookingOne" time="5.986"/>
  <testcase classname="prashantbhakuni.Test.AppointmentBookingTestCases" name="bookingThree" time="6.001"/>
  <testcase classname="prashantbhakuni.Test.AppointmentBookingTestCases" name="bookingTwo" time="5.547"/>
  <testcase classname="prashantbhakuni.Test.AppointmentBookingTestCases" name="bookingSix" time="5.545">
    <failure message="expected [Please select a valid date] but found [Appointment Confirmation]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please select a valid date] but found [Appointment Confirmation]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at prashantbhakuni.Test.AppointmentBookingTestCases.bookingSix(AppointmentBookingTestCases.java:199)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- bookingSix -->
  <testcase classname="prashantbhakuni.Test.AppointmentBookingTestCases" name="bookingFour" time="6.938"/>
</testsuite> <!-- prashantbhakuni.Test.AppointmentBookingTestCases -->
